// <auto-generated />
namespace Gokhan_Selale_Project.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mgrtn7 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mgrtn7));
        
        string IMigrationMetadata.Id
        {
            get { return "202005162001436_mgrtn7"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
